### ISSUE TITLE
预测问题

### ISSUE THREAD

**Issue by FredlinT** [shiyuzh2007/ASR#2]
在训练一段时间后损失函数无法下降，在预测时出来的都是同一个字，想请问您与有没有出现过这种情况？

**Comment by wxy1988** [comment]
我的经验是学习率降到0.2以内，基本不会收敛不了。

**Comment by shiyuzh2007** [comment]
我这边是采用的学习率是warmup方式，learning_rate设置为1，warmup_steps设置为12000。训练到大约6000步左右时在tensorboad中可以看到对齐现象。如果训练6000步后变成竖线则表示训练失败了。

**Comment by Coastchb** [comment]
@FredlinT  我也遇到同样的问题。  预测出来的都是 一个字 + 多个"/s"

**Comment by Coastchb** [comment]
@shiyuzh2007 
训练到120k步，对齐还是不好
![decoder_attention_0](https://user-images.githubusercontent.com/19300820/54422678-faf42600-4749-11e9-9c0f-016735406429.png)
![decoder_attention_1](https://user-images.githubusercontent.com/19300820/54422680-faf42600-4749-11e9-9124-d60008b0ab08.png)


遇到训练失败的情况，请问你是怎么调成功的呢？

**Comment by shiyuzh2007** [comment]
@Coastchb
1.首先特征需要做拼帧跳帧的预处理；
2.可以把grads_clip: 5，设置低一点。如果还不行，把学习率也设置低一点。先把模型训练收敛以后再将这些参数增加。我提供的配置是在8块GPU上运行的参数，所以可能跟你的环境不太一样。

**Comment by Coastchb** [comment]
@shiyuzh2007 
拼帧跳帧已做过。
看来还是训练时超参的问题。
多谢了

**Comment by wylqq312715289** [comment]
数据集的链接可以发一下吗？

**Comment by Hui-Ling** [comment]
同一個模型參數設定，用在aishell資料集訓練效果很好，但是用來訓練其他的資料集時，預測的序列幾乎都是由單一個字組成。請問這有什麼建議嗎?

**Comment by shiyuzh2007** [comment]
@Hui-Ling 如果预测的结果全部是单一个字，这种情况表示模型没有收敛，需要继续训练，这个是我碰到这个问题时的解决办法。
