### ISSUE TITLE
OOM problem while training

### ISSUE THREAD

**Issue by Coastchb** [shiyuzh2007/ASR#3]
Hi,
我尝试复现HKUST实验，配置文件用的是：config_template_char_unit512_block6_left3_big_dim80_sp.yaml

我的实验环境受限，只能用3块GPU卡（TITAN X 12G)。
总出现OOM问题，我试着把bucket_step和tokens_per_batch调为默认值的1/3甚至更小，但还是有OOM问题。
请问有任何建议吗？

**Comment by shiyuzh2007** [comment]
这个问题应该是训练快结束时报出OOV问题，解决的办法是在配置文件中增加min_count_in_bucket=20（utils.py文件里面会读这个参数，否则会使用默认值default_min_count_in_bucket =100），应该是这个问题导致你OOM。

**Comment by Coastchb** [comment]
感谢。之前的OOM是在训练到4k个step左右报的，所以还不是快结束。
我目前是修改了数据加载方式，每个step读一个batch，没有bucket机制。 tokens_per_batch设的比较小，所以每个step的训练数据比较少，20条语音左右。（还不知道会不会影响到收敛速度）
