### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by DDDominik** [shiyuzh2007/ASR#6]
你好，请问可以看到yaml中所用到的数据格式例子吗？

**Comment by shiyuzh2007** [comment]
src_path是拼三帧调三帧进行的特征提取，直接使用的kalid命令提取的。
apply-cmvn --norm-vars=true cmvn_glob.mat scp:feats.scp ark:- | splice-feats --left-context=3 --right-context=0 ark:- ark:- |   subsample-feats --n=3 ark:- ark,scp:feats.ark.left3_sub3,feats.scp.left3_sub3
dst_path是按空格分隔的字，例如：
20040527_210939_A901153_B901154-A-001537-002423 呃 像 泰 山 了 华 山 五 台 山 九 华 山 很 多 啦
